### ISSUE TITLE
Not updated for current patch

### ISSUE THREAD

**Issue by CaptainNewbi** [stormgateworld/overlay#2]
Does not reference correct webpage.
Does not have support for new faction.
Does not have support for new website features.

**Comment by robertvanhoesel** [comment]
> The new Official API is in an early stage, and the data and rate limits currently available are insufficient to support the features we have developed. We have made the decision to pause our plans for an open-source, user-friendly, and community-driven platform while we follow how the Official APIs evolve.

https://stormgateworld.com/discontinued/
